name: deployement
on: [push,workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v3
      - name: install depenedencies
        run: npm ci
      - name: Run linting
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build 
        run: npm run build
      - name: log build
        run: echo "build successful....."
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build 
        run: npm run test
      - name: log test
        run: echo "test successful....."
  deploy:
    runs-on: ubuntu-latest
    needs: [lint,build,test]
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: deployement
        run: echo "deployement completed-------"