name: deployement
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run test cases
        run: npm run test
      - name: build the repository
        run: npm run build
      - name: deploy
        run: echo "depoying the project"
