name: event filters test
on:
  push:
    branches:
      - main
      - "feat/**"
      - "dev-*"
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run test cases
        run: npm run test
      - name: Build the repository
        run: npm run build
      - name: Deploy
        run: echo "deploying the project========"
